// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknk2-GyMOC5t7Nn_h1pw_kQlHRII9_4s',
    appId: '1:633065544714:web:566f5f3702d47503fd53f3',
    messagingSenderId: '633065544714',
    projectId: 'mobeng-a6775',
    authDomain: 'mobeng-a6775.firebaseapp.com',
    storageBucket: 'mobeng-a6775.firebasestorage.app',
    measurementId: 'G-5876T5QXSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaeFoSc6Ap9a_3jGzN9ka8IbtSEZB_bz4',
    appId: '1:633065544714:android:055a3c8e435ec425fd53f3',
    messagingSenderId: '633065544714',
    projectId: 'mobeng-a6775',
    storageBucket: 'mobeng-a6775.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTk2bZlr-mMmpjXwDsG4ZuOCIz2r9r-OU',
    appId: '1:633065544714:ios:e208a93ef1aca260fd53f3',
    messagingSenderId: '633065544714',
    projectId: 'mobeng-a6775',
    storageBucket: 'mobeng-a6775.firebasestorage.app',
    iosClientId: '633065544714-j3199q6884krp2tli4hi5h83tqrhu1vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasMp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTk2bZlr-mMmpjXwDsG4ZuOCIz2r9r-OU',
    appId: '1:633065544714:ios:e208a93ef1aca260fd53f3',
    messagingSenderId: '633065544714',
    projectId: 'mobeng-a6775',
    storageBucket: 'mobeng-a6775.firebasestorage.app',
    iosClientId: '633065544714-j3199q6884krp2tli4hi5h83tqrhu1vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasMp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDknk2-GyMOC5t7Nn_h1pw_kQlHRII9_4s',
    appId: '1:633065544714:web:3798cf9be35c6bc3fd53f3',
    messagingSenderId: '633065544714',
    projectId: 'mobeng-a6775',
    authDomain: 'mobeng-a6775.firebaseapp.com',
    storageBucket: 'mobeng-a6775.firebasestorage.app',
    measurementId: 'G-HF0CX6290K',
  );

}